### ISSUE TITLE
convert squad examples to features very slow

### ISSUE THREAD

**Issue by Saibo-creator** [TheAtticusProject/cuad#12]
Hello,
        The step to convert squad examples to features is very slow on my machine:48 cores + GPU. The tqdm estimates 24 hours to finish. Is it normal? Thanks!

```convert squad examples to features:   4%|██                                                     | 865/22450 [20:16<24:52:42,  4.15s/it]```

**Comment by Saibo-creator** [comment]
--threads argument helps

**Comment by huberemanuel** [comment]
Could you share the number of threads you used and the amount of memory that you have? Thanks!
