### ISSUE TITLE
Checkpoints location

### ISSUE THREAD

**Issue by gitcarbs** [TheAtticusProject/cuad#2]
I couldn't locate them in the provided documentation, do you mind pointing or linking to them in README?

```
We provide checkpoints for three of the best models fine-tuned on CUAD: RoBERTa-base (~100M parameters), RoBERTa-large (~300M parameters), and DeBERTa-xlarge (~900M parameters).
```

**Comment by TheAtticusProject** [comment]
We apologize for the delay. We have just added a link to the three checkpoints.

**Comment by TheAtticusProject** [comment]
Thanks for noting this. This issue should be resolved now. Let me know if
not.
