### ISSUE TITLE
Inference pipeline for sample question and answering

### ISSUE THREAD

**Issue by deepak-singh29** [TheAtticusProject/cuad#4]
Please share the code if available to get inference on standard paragraph and question.

**Comment by TheAtticusProject** [comment]
We include evaluation code for the format we use for CUAD. Please let us know if there's something more specific that you're looking for that is not already included in the provided code.

**Comment by Alfin72** [comment]
I would like to pass in my own data and test the model, Would appreciate if you could help with a collab for the inference pipeline.
