### ISSUE TITLE
Predictions take a lot of time.

### ISSUE THREAD

**Issue by deepakumarln** [TheAtticusProject/cuad#8]
Hi

When using the Deberta model for predictions, it takes more than an hour for one document (85 page document). Is there any way to reduce the time taken?, please advise on this. 
Thanks in advance.

**Comment by hendrycks** [comment]
DeBERTa is a particularly large model and will only be fast with state-of-the-art GPUs. We suggest using a smaller model if inference speed is a concern.

**Comment by deepakumarln** [comment]
thank you for the quick reply, it takes around 1 hour on a Tesla M60 GPU for a single document (85 page document).
